
# -*- coding: utf-8 -*-

texts = {
    "English": {
        "app_title": "VRCT-TTS",
        "websocket_server_url": "WebSocket Server URL",
        "connect_websocket": "Connect WebSocket",
        "disconnect_websocket": "Disconnect WebSocket",
        "websocket_status_connected": "WebSocket: Connected",
        "websocket_status_disconnected": "WebSocket: Disconnected",
        "output_device": "Output Device",
        "secondary_output_device": "Secondary Output Device",
        "enable_secondary_speaker": "Enable Secondary Speaker",
        "voicevox_settings": "VOICEVOX Settings",
        "character_selection": "Character Selection",
        "voice_style": "Voice Style",
        "source_tts_settings": "TTS Settings (Source)",
        "play_source_text": "Play text before translation",
        "dest_tts_settings": "TTS Settings (Destination)",
        "play_dest_text": "Play text after translation",
        "volume": "Volume",
        "speed": "Speed",
        "playback": "Playback",
        "gtts_language_for_test": "gTTS Language for Test",
        "play_voicevox": "Play (VOICEVOX)",
        "play_gtts": "Play (gTTS)",
        "stop_and_clear": "Stop and Clear",
        "status_ready": "Ready",
        "status_loading_data": "Loading data...",
        "status_audio_device_error": "Error loading audio devices: ",
        "status_voicevox_connection_error": "Could not connect to VOICEVOX Engine.",
        "status_audio_device_loaded": "Audio devices loaded.",
        "status_voicevox_loaded": "VOICEVOX loaded.",
        "status_loading_hosts": "Loading hosts...",
        "status_loading_devices": "Loading devices...",
        "status_loading_characters": "Loading characters...",
        "status_loading_styles": "Loading styles...",
        "status_voicevox_unavailable": "VOICEVOX Unavailable",
        "host_all": "All",
        "device_default": "Default",
        "config_saved": "Configuration saved.",
        "status_ws_connected": "Connected to WebSocket server.",
        "status_ws_disconnected": "Disconnected from WebSocket server.",
        "error_no_style_selected": "Error: No speaker style selected.",
        "status_ws_connecting": "Connecting to WebSocket server: ",
        "error_message_processing": "Message processing error: ",
        "status_received_message": "Received: ",
        "status_style_auto_selected": "Style auto-selected: ",
        "error_no_text_input": "Error: No text input.",
        "status_synthesizing": "Synthesizing audio...",
        "status_playback_complete": "Playback complete.",
        "error_synthesis": "Error: ",
        "error_gtts_unsupported_source": "gTTS unsupported language (Source): ",
        "error_gtts_unsupported_dest": "gTTS unsupported language (Dest): ",
        "status_stop_request_received": "Stop request received. Clearing and stopping audio...",
        "status_active_playback_stopped": "Stopped active playback.",
        "error_speaker_stop": "Speaker stop error: ",
        "status_no_active_playback": "No active playback to stop.",
    },
    "日本語": {
        "app_title": "VRCT-TTS",
        "websocket_server_url": "WebSocketサーバーURL",
        "connect_websocket": "WebSocket接続開始",
        "disconnect_websocket": "WebSocket接続停止",
        "websocket_status_connected": "WebSocket: 接続済み",
        "websocket_status_disconnected": "WebSocket: 未接続",
        "output_device": "出力デバイス",
        "secondary_output_device": "第2出力デバイス",
        "enable_secondary_speaker": "第2スピーカーを有効にする",
        "voicevox_settings": "VOICEVOX設定",
        "character_selection": "キャラクター選択",
        "voice_style": "声のスタイル",
        "source_tts_settings": "翻訳前 (Source) のTTS設定",
        "play_source_text": "翻訳前のテキストを再生する",
        "dest_tts_settings": "翻訳後 (Destination) のTTS設定",
        "play_dest_text": "翻訳後のテキストを再生する",
        "volume": "音量",
        "speed": "再生速度",
        "playback": "再生",
        "gtts_language_for_test": "gTTS言語 (テスト用)",
        "play_voicevox": "再生 (VOICEVOX)",
        "play_gtts": "再生 (gTTS)",
        "stop_and_clear": "再生停止とクリア",
        "status_ready": "準備完了",
        "status_loading_data": "データを読み込み中...",
        "status_audio_device_error": "オーディオデバイス読込エラー: ",
        "status_voicevox_connection_error": "VOICEVOX Engineに接続できません。",
        "status_audio_device_loaded": "オーディオデバイスの読み込みが完了しました",
        "status_voicevox_loaded": "VOICEVOXの読み込みが完了しました",
        "status_loading_hosts": "ホストを読み込み中...",
        "status_loading_devices": "デバイスを読み込み中...",
        "status_loading_characters": "キャラクターを読み込み中...",
        "status_loading_styles": "スタイルを読み込み中...",
        "status_voicevox_unavailable": "VOICEVOX利用不可",
        "host_all": "すべて",
        "device_default": "デフォルト",
        "config_saved": "設定を保存しました",
        "status_ws_connected": "WebSocketサーバーに接続しました",
        "status_ws_disconnected": "WebSocket接続を終了しました",
        "error_no_style_selected": "エラー: スピーカースタイルが選択されていません",
        "status_ws_connecting": "WebSocketサーバーに接続中: ",
        "error_message_processing": "メッセージ処理エラー: ",
        "status_received_message": "受信: ",
        "status_style_auto_selected": "スタイルが自動選択されました: ",
        "error_no_text_input": "エラー: テキストが入力されていません",
        "status_synthesizing": "音声を合成中...",
        "status_playback_complete": "再生完了",
        "error_synthesis": "エラー: ",
        "error_gtts_unsupported_source": "gTTS非対応言語(Source): ",
        "error_gtts_unsupported_dest": "gTTS非対応言語(Dest): ",
        "status_stop_request_received": "停止リクエスト受信。オーディオをクリア・停止処理を開始します...",
        "status_active_playback_stopped": "アクティブな再生を停止しました。",
        "error_speaker_stop": "スピーカー停止エラー: ",
        "status_no_active_playback": "停止するアクティブな再生はありません。",
    }
}
